"""add application submission tracking

Revision ID: 385b938a8fbf
Revises: 40be197ee458
Create Date: 2026-09-21 14:57:52.364669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '385b938a8fbf'
down_revision: Union[str, Sequence[str], None] = '40be197ee458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'candidates',
    sa.Column(
        'application_submitted',
        sa.Boolean(),
        nullable=False,
        server_default=sa.false()
    )
)
    op.add_column('candidates', sa.Column('application_submitted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'application_submitted_at')
    op.drop_column('candidates', 'application_submitted')
    # ### end Alembic commands ###
